export {
  WarningCircle as AlertCircle, Warning as AlertTriangle, ArrowLeft, ArrowRight,
  Prohibit as Ban, BookOpen, Calendar, Check, CheckCircle, CheckCircle as CheckCircle2,
  CheckSquare, CaretDown as ChevronDown, CaretLeft as ChevronLeft, CaretRight as ChevronRight,
  Question as CircleHelp, Clock as Clock3, Cloud, Copy, Database, DownloadSimple as Download,
  ArrowSquareOut as ExternalLink, Eye, EyeSlash as EyeOff, File, Files as FileStack, FileText,
  Funnel as Filter, Folder, FolderSimplePlus as FolderInput, FolderOpen,
  FolderPlus, FolderSimple as FolderRoot, Gauge, Globe, HardDrives as HardDrive,
  Image, Info, Key as KeyRound, Translate as Languages, SquaresFour as LayoutGrid,
  ListBullets as List, ListChecks, FunnelSimple as ListFilter, CircleNotch as LoaderCircle,
  Lock, SignIn as LogIn, SignOut as LogOut, ArrowsOut as Maximize2, List as Menu,
  Monitor, Moon, DotsThreeVertical as MoreVertical, MusicNote as Music,
  TreeStructure as Network, Package, Package as PackageCheck, Palette, PencilSimple as Pencil,
  Plus, Power, Power as PowerOff, ArrowsClockwise as RefreshCw, ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search, MagnifyingGlassMinus as SearchX, HardDrives as Server,
  GearSix as Settings, ShareNetwork as Share2, Shield, ShieldWarning as ShieldAlert,
  ShieldCheck, Sparkle as Sparkles, Square, Star, Sun, Trash as Trash2,
  UploadSimple as Upload, CloudArrowUp as UploadCloud, UserCircle as UserRound,
  UserMinus as UserX, VideoCamera as Video, WifiSlash as WifiOff, X, XCircle,
  MagnifyingGlassPlus as ZoomIn, MagnifyingGlassMinus as ZoomOut,
} from '@phosphor-icons/react';
